"""
Monster v2.0.0 Configuration Module

Contains all detection patterns, wordlists, signatures, and configuration
constants used throughout the Monster toolkit.
"""

import os
import re
import json
from pathlib import Path


# =============================================================================
# GENERAL CONSTANTS
# =============================================================================

DEFAULT_USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
RATE_LIMIT_DELAY = 1.0
MAX_THREADS = 10
TIMEOUT = 15
MAX_RETRIES = 3
OUTPUT_DIR = "monster_output"


# =============================================================================
# COMMON PORTS
# =============================================================================

COMMON_PORTS = [
    21, 22, 23, 25, 53, 80, 110, 111, 135, 139, 143, 161, 389, 443, 445,
    465, 587, 636, 993, 995, 1433, 1521, 2049, 2082, 2083, 2086, 2087,
    3306, 3389, 5432, 5900, 5985, 6379, 8000, 8008, 8080, 8081, 8443,
    8888, 9090, 9200, 9300, 10000, 11211, 27017, 27018, 28017, 50000
]


# =============================================================================
# SECRET DETECTION PATTERNS (80+ patterns)
# =============================================================================

PATTERNS = {
    # AWS Credentials
    "AWS Access Key ID": r"(?:A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}",
    "AWS Secret Access Key": r"(?i)aws[\-_]?secret[\-_]?access[\-_]?key[\s=:]+[A-Za-z0-9/+=]{40}",
    "AWS MWS Key": r"amzn\.mws\.[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}",
    "AWS Session Token": r"(?i)aws[\-_]?session[\-_]?token[\s=:]+[A-Za-z0-9/+=]{100,}",
    "AWS ARN": r"arn:aws:[a-z0-9\-]+:[a-z0-9\-]*:\d{12}:[a-zA-Z0-9\-_/]+",

    # Google/GCP
    "Google API Key": r"AIza[0-9A-Za-z\-_]{35}",
    "Google Cloud Platform API Key": r"(?i)google[\-_]?cloud[\-_]?api[\-_]?key[\s=:]+[A-Za-z0-9_\-]{20,}",
    "Google OAuth Access Token": r"ya29\.[0-9A-Za-z\-_]+",
    "Google OAuth Client ID": r"[0-9]+-[0-9A-Za-z_]{32}\.apps\.googleusercontent\.com",
    "Google Service Account": r"\"type\":\s*\"service_account\"",
    "Firebase Cloud Messaging": r"AAAA[A-Za-z0-9_-]{7}:[A-Za-z0-9_-]{140}",
    "Firebase Database URL": r"https://[a-z0-9-]+\.firebaseio\.com",

    # Azure
    "Azure Storage Account Key": r"(?i)azure[\-_]?storage[\-_]?(?:account[\-_]?)?key[\s=:]+[A-Za-z0-9/+=]{88}",
    "Azure Connection String": r"DefaultEndpointsProtocol=https;AccountName=[^;]+;AccountKey=[A-Za-z0-9/+=]{88}",
    "Azure AD Client Secret": r"(?i)azure[\-_]?(?:ad[\-_]?)?client[\-_]?secret[\s=:]+[A-Za-z0-9_\-~.]{34,}",
    "Azure SAS Token": r"[?&]sig=[A-Za-z0-9%/+=]+&se=[0-9]+",
    "Azure DevOps PAT": r"(?i)azure[\-_]?devops[\-_]?pat[\s=:]+[a-z0-9]{52}",

    # GitHub
    "GitHub Personal Access Token": r"ghp_[0-9a-zA-Z]{36}",
    "GitHub OAuth Access Token": r"gho_[0-9a-zA-Z]{36}",
    "GitHub App Token": r"(?:ghu|ghs)_[0-9a-zA-Z]{36}",
    "GitHub Fine-Grained Token": r"github_pat_[0-9a-zA-Z_]{82}",
    "GitHub Refresh Token": r"ghr_[0-9a-zA-Z]{36}",

    # GitLab
    "GitLab Personal Access Token": r"glpat-[0-9a-zA-Z\-_]{20}",
    "GitLab Pipeline Token": r"glpt-[0-9a-zA-Z\-_]{20}",
    "GitLab Runner Token": r"glrt-[0-9a-zA-Z\-_]{20}",
    "GitLab Deploy Token": r"gldt-[0-9a-zA-Z\-_]{20}",

    # Slack
    "Slack Bot Token": r"xoxb-[0-9]{11}-[0-9]{11}-[0-9a-zA-Z]{24}",
    "Slack User Token": r"xoxp-[0-9]{11}-[0-9]{11}-[0-9a-zA-Z]{24}",
    "Slack Webhook URL": r"https://hooks\.slack\.com/services/T[a-zA-Z0-9_]+/B[a-zA-Z0-9_]+/[a-zA-Z0-9_]+",
    "Slack App Token": r"xapp-[0-9]-[A-Z0-9]+-[0-9]+-[a-z0-9]+",
    "Slack Config Token": r"xoxe\.xoxp-1-[A-Za-z0-9-]+",

    # Discord
    "Discord Bot Token": r"[MN][A-Za-z\d]{23,}\.[\w-]{6}\.[\w-]{27}",
    "Discord Webhook URL": r"https://discord(?:app)?\.com/api/webhooks/[0-9]+/[A-Za-z0-9_-]+",

    # Payment Processors
    "Stripe Secret Key": r"sk_live_[0-9a-zA-Z]{24,}",
    "Stripe Publishable Key": r"pk_live_[0-9a-zA-Z]{24,}",
    "Stripe Restricted Key": r"rk_live_[0-9a-zA-Z]{24,}",
    "Stripe Webhook Secret": r"whsec_[0-9a-zA-Z]{32,}",
    "Square Access Token": r"sq0atp-[0-9A-Za-z\-_]{22}",
    "Square OAuth Secret": r"sq0csp-[0-9A-Za-z\-_]{43}",
    "PayPal Braintree Access Token": r"access_token\$production\$[0-9a-z]{16}\$[0-9a-f]{32}",
    "PayPal Client ID": r"(?i)paypal[\-_]?client[\-_]?id[\s=:]+[A-Za-z0-9_\-]{80}",

    # Communication Services
    "Twilio API Key": r"SK[0-9a-fA-F]{32}",
    "Twilio Account SID": r"AC[a-zA-Z0-9_\-]{32}",
    "Twilio Auth Token": r"(?i)twilio[\-_]?auth[\-_]?token[\s=:]+[0-9a-f]{32}",
    "SendGrid API Key": r"SG\.[0-9A-Za-z\-_]{22}\.[0-9A-Za-z\-_]{43}",
    "Mailgun API Key": r"key-[0-9a-zA-Z]{32}",
    "Mailchimp API Key": r"[0-9a-f]{32}-us[0-9]{1,2}",
    "Postmark Server Token": r"(?i)postmark[\-_]?(?:server[\-_]?)?token[\s=:]+[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}",

    # Cloud Providers
    "Heroku API Key": r"(?i)heroku[\-_]?api[\-_]?key[\s=:]+[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}",
    "DigitalOcean Token": r"dop_v1_[a-f0-9]{64}",
    "DigitalOcean OAuth Token": r"(?i)digitalocean[\-_]?(?:oauth[\-_]?)?token[\s=:]+[a-f0-9]{64}",
    "Cloudflare API Key": r"(?i)cloudflare[\-_]?api[\-_]?key[\s=:]+[0-9a-f]{37}",
    "Cloudflare API Token": r"(?i)cf[\-_]?api[\-_]?token[\s=:]+[A-Za-z0-9_\-]{40}",
    "Linode API Token": r"(?i)linode[\-_]?(?:api[\-_]?)?token[\s=:]+[a-f0-9]{64}",
    "Vultr API Key": r"(?i)vultr[\-_]?api[\-_]?key[\s=:]+[A-Z0-9]{36}",

    # Package Managers & CI
    "NPM Token": r"(?:npm_[A-Za-z0-9]{36}|//registry\.npmjs\.org/:_authToken=[A-Za-z0-9\-._]+)",
    "PyPI Token": r"pypi-[A-Za-z0-9_\-]{50,}",
    "NuGet API Key": r"oy2[a-z0-9]{43}",
    "Artifactory API Token": r"(?i)artifactory[\-_]?(?:api[\-_]?)?(?:token|key)[\s=:]+[A-Za-z0-9_\-]{73}",
    "Docker Registry Token": r"(?i)docker[\-_]?(?:registry[\-_]?)?token[\s=:]+[A-Za-z0-9_\-]{20,}",
    "CircleCI Token": r"(?i)circle[\-_]?ci[\-_]?token[\s=:]+[a-f0-9]{40}",
    "Travis CI Token": r"(?i)travis[\-_]?(?:ci[\-_]?)?token[\s=:]+[A-Za-z0-9]{22}",
    "Jenkins API Token": r"(?i)jenkins[\-_]?(?:api[\-_]?)?token[\s=:]+[a-f0-9]{32,}",

    # Database Connection Strings
    "MongoDB Connection String": r"mongodb(?:\+srv)?://[^\s<>\"]+",
    "PostgreSQL Connection String": r"postgres(?:ql)?://[^\s<>\"]+",
    "MySQL Connection String": r"mysql://[^\s<>\"]+",
    "Redis Connection String": r"redis://[^\s<>\"]+",
    "MSSQL Connection String": r"Server=[^;]+;Database=[^;]+;(?:User Id|Uid)=[^;]+;(?:Password|Pwd)=[^;]+",
    "JDBC Connection String": r"jdbc:[a-z]+://[^\s<>\"]+",
    "CouchDB Connection String": r"(?i)couchdb://[^\s<>\"]+",

    # SSH & Crypto Keys
    "SSH Private Key": r"-----BEGIN (?:RSA|DSA|EC|OPENSSH) PRIVATE KEY-----",
    "PGP Private Key": r"-----BEGIN PGP PRIVATE KEY BLOCK-----",
    "Generic Private Key": r"-----BEGIN PRIVATE KEY-----",
    "SSH Public Key": r"ssh-(?:rsa|dss|ed25519) AAAA[A-Za-z0-9+/]+",
    "X509 Certificate": r"-----BEGIN CERTIFICATE-----",

    # Tokens & OAuth
    "Generic Bearer Token": r"(?i)bearer[\s]+[A-Za-z0-9\-._~+/]+=*",
    "Generic OAuth Token": r"(?i)(?:oauth|access)[\-_]?token[\s=:]+[A-Za-z0-9\-._~+/]{20,}",
    "JWT Token": r"eyJ[A-Za-z0-9_\-]*\.eyJ[A-Za-z0-9_\-]*\.[A-Za-z0-9_\-]*",
    "Basic Auth Header": r"(?i)authorization:\s*basic\s+[A-Za-z0-9+/=]+",

    # SMTP/FTP Credentials
    "SMTP Credentials": r"(?i)smtp[\-_]?(?:pass(?:word)?|credentials?)[\s=:]+[^\s]+",
    "FTP Credentials": r"ftp://[^:]+:[^@]+@[^\s]+",

    # Miscellaneous
    "Shopify App Secret": r"shpss_[a-fA-F0-9]{32}",
    "Shopify Access Token": r"shpat_[a-fA-F0-9]{32}",
    "Shopify Custom Token": r"shpca_[a-fA-F0-9]{32}",
    "Telegram Bot Token": r"[0-9]+:AA[0-9A-Za-z\-_]{33}",
    "Facebook Access Token": r"EAACEdEose0cBA[0-9A-Za-z]+",
    "Twitter Bearer Token": r"(?i)twitter[\-_]?bearer[\-_]?token[\s=:]+AAAAAAAAAAAAAAAAAAAAAA[A-Za-z0-9%]+",
    "Okta API Token": r"(?i)okta[\-_]?api[\-_]?token[\s=:]+[0-9a-zA-Z_\-]{42}",
    "Datadog API Key": r"(?i)datadog[\-_]?api[\-_]?key[\s=:]+[a-f0-9]{32}",
    "New Relic API Key": r"NRAK-[A-Z0-9]{27}",
    "Sentry DSN": r"https://[a-f0-9]+@(?:o[0-9]+\.)?sentry\.io/[0-9]+",
    "Algolia API Key": r"(?i)algolia[\-_]?(?:api[\-_]?)?key[\s=:]+[a-f0-9]{32}",
    "Zendesk API Token": r"(?i)zendesk[\-_]?(?:api[\-_]?)?token[\s=:]+[A-Za-z0-9]{40}",
    "Linear API Key": r"lin_api_[A-Za-z0-9]{40}",
    "Doppler API Token": r"dp\.pt\.[A-Za-z0-9]{43}",
    "Generic API Key": r"(?i)(?:api[\-_]?key|apikey|api_secret|app_key|app_secret|client_secret)[\s=:\"]+[A-Za-z0-9_\-]{16,}",
    "Generic Secret": r"(?i)(?:secret|password|passwd|pwd|token)[\s=:\"]+[^\s\"]{8,}",
}


# =============================================================================
# SUBDOMAIN TAKEOVER FINGERPRINTS (30+ services)
# =============================================================================

TAKEOVER_FINGERPRINTS = {
    "AWS S3": {
        "cnames": ["s3.amazonaws.com", "s3-website", ".s3.amazonaws.com"],
        "fingerprints": ["NoSuchBucket", "The specified bucket does not exist"],
        "vulnerable": True,
    },
    "AWS CloudFront": {
        "cnames": ["cloudfront.net"],
        "fingerprints": ["Bad request", "ERROR: The request could not be satisfied"],
        "vulnerable": True,
    },
    "AWS Elastic Beanstalk": {
        "cnames": ["elasticbeanstalk.com"],
        "fingerprints": ["NXDOMAIN"],
        "vulnerable": True,
    },
    "GitHub Pages": {
        "cnames": ["github.io"],
        "fingerprints": ["There isn't a GitHub Pages site here", "For root URLs (like http://example.com/)"],
        "vulnerable": True,
    },
    "Heroku": {
        "cnames": ["herokuapp.com", "herokussl.com", "herokudns.com"],
        "fingerprints": ["No such app", "no-such-app", "herokucdn.com/error-pages/no-such-app"],
        "vulnerable": True,
    },
    "Shopify": {
        "cnames": ["myshopify.com"],
        "fingerprints": ["Sorry, this shop is currently unavailable", "Only one step left"],
        "vulnerable": True,
    },
    "Tumblr": {
        "cnames": ["tumblr.com"],
        "fingerprints": ["Whatever you were looking for doesn't currently exist at this address"],
        "vulnerable": True,
    },
    "WordPress.com": {
        "cnames": ["wordpress.com"],
        "fingerprints": ["Do you want to register"],
        "vulnerable": True,
    },
    "Pantheon": {
        "cnames": ["pantheonsite.io"],
        "fingerprints": ["404 error unknown site", "The gods are wise"],
        "vulnerable": True,
    },
    "Fastly": {
        "cnames": ["fastly.net", "fastlylb.net", "global.ssl.fastly.net"],
        "fingerprints": ["Fastly error: unknown domain"],
        "vulnerable": True,
    },
    "Ghost": {
        "cnames": ["ghost.io"],
        "fingerprints": ["The thing you were looking for is no longer here"],
        "vulnerable": True,
    },
    "Surge.sh": {
        "cnames": ["surge.sh"],
        "fingerprints": ["project not found"],
        "vulnerable": True,
    },
    "Zendesk": {
        "cnames": ["zendesk.com"],
        "fingerprints": ["Help Center Closed", "this help center no longer exists"],
        "vulnerable": True,
    },
    "Teamwork": {
        "cnames": ["teamwork.com"],
        "fingerprints": ["Oops - We didn't find your site"],
        "vulnerable": True,
    },
    "Helpjuice": {
        "cnames": ["helpjuice.com"],
        "fingerprints": ["We could not find what you're looking for"],
        "vulnerable": True,
    },
    "HelpScout": {
        "cnames": ["helpscoutdocs.com"],
        "fingerprints": ["No settings were found for this company"],
        "vulnerable": True,
    },
    "Cargo Collective": {
        "cnames": ["cargocollective.com"],
        "fingerprints": ["404 Not Found"],
        "vulnerable": True,
    },
    "UserVoice": {
        "cnames": ["uservoice.com"],
        "fingerprints": ["This UserVoice subdomain is currently available"],
        "vulnerable": True,
    },
    "Statuspage": {
        "cnames": ["statuspage.io"],
        "fingerprints": ["You are being redirected", "statuspage.io"],
        "vulnerable": True,
    },
    "Intercom": {
        "cnames": ["custom.intercom.help"],
        "fingerprints": ["This page is reserved for artistic dogs", "Uh oh. That page doesn't exist"],
        "vulnerable": True,
    },
    "Webflow": {
        "cnames": ["proxy.webflow.com", "proxy-ssl.webflow.com"],
        "fingerprints": ["The page you are looking for doesn't exist or has been moved"],
        "vulnerable": True,
    },
    "Kajabi": {
        "cnames": ["endpoint.mykajabi.com"],
        "fingerprints": ["The page you were looking for doesn't exist"],
        "vulnerable": True,
    },
    "Thinkific": {
        "cnames": ["thinkific.com"],
        "fingerprints": ["You may have mistyped the address or the page may have moved"],
        "vulnerable": True,
    },
    "Tave": {
        "cnames": ["clientaccess.tave.com"],
        "fingerprints": ["Error 404 - Page Not Found"],
        "vulnerable": False,
    },
    "Wishpond": {
        "cnames": ["wishpond.com"],
        "fingerprints": ["https://www.wishpond.com/404"],
        "vulnerable": True,
    },
    "Aftership": {
        "cnames": ["aftership.com"],
        "fingerprints": ["Oops, page not found"],
        "vulnerable": True,
    },
    "Aha": {
        "cnames": ["ideas.aha.io"],
        "fingerprints": ["There is no portal here", "Want to set up your own Ideas portal"],
        "vulnerable": True,
    },
    "Brightcove": {
        "cnames": ["bcvp0rtal.com", "brightcovegallery.com", "gallery.video"],
        "fingerprints": ["Error - Loss of video platform"],
        "vulnerable": True,
    },
    "Bigcartel": {
        "cnames": ["bigcartel.com"],
        "fingerprints": ["<h1>Oops! We couldn&#8217;t find that page.</h1>"],
        "vulnerable": True,
    },
    "Campaignmonitor": {
        "cnames": ["createsend.com", "name.createsend.com"],
        "fingerprints": ["Trying to access your account?", "signup"],
        "vulnerable": True,
    },
    "Acquia": {
        "cnames": ["acquia-test.co"],
        "fingerprints": ["Web Site Not Found", "If you are an Acquia Cloud customer"],
        "vulnerable": True,
    },
    "Simplebooklet": {
        "cnames": ["simplebooklet.com"],
        "fingerprints": ["Simplebooklet: The tool for creating"],
        "vulnerable": True,
    },
    "GetResponse": {
        "cnames": [".gr8.com"],
        "fingerprints": ["With GetResponse, landing pages"],
        "vulnerable": True,
    },
    "Vend": {
        "cnames": ["vendecommerce.com"],
        "fingerprints": ["Looks like you've traveled too far into cyberspace"],
        "vulnerable": True,
    },
    "Netlify": {
        "cnames": ["netlify.app", "netlify.com"],
        "fingerprints": ["Not Found - Request ID"],
        "vulnerable": True,
    },
    "Fly.io": {
        "cnames": ["fly.dev"],
        "fingerprints": ["404 Not Found"],
        "vulnerable": True,
    },
}


# =============================================================================
# SECURITY HEADERS
# =============================================================================

SECURITY_HEADERS = [
    "Strict-Transport-Security",
    "Content-Security-Policy",
    "X-Content-Type-Options",
    "X-Frame-Options",
    "X-XSS-Protection",
    "Referrer-Policy",
    "Permissions-Policy",
    "Cross-Origin-Embedder-Policy",
    "Cross-Origin-Opener-Policy",
    "Cross-Origin-Resource-Policy",
    "X-Permitted-Cross-Domain-Policies",
    "Expect-CT",
    "Cache-Control",
    "Pragma",
]


# =============================================================================
# CORS TEST ORIGINS
# =============================================================================

CORS_TEST_ORIGINS = [
    "https://evil.com",
    "https://attacker.com",
    "null",
    "https://sub.evil.com",
    "https://evil.{target}",
    "https://{target}.evil.com",
    "https://{target}evil.com",
    "https://evil{target}.com",
    "http://{target}",
    "https://{target}.attacker.com",
    "https://not{target}",
    "https://{target}%60.evil.com",
    "https://{target}_.evil.com",
]


# =============================================================================
# TECHNOLOGY SIGNATURES
# =============================================================================

TECH_SIGNATURES = {
    "headers": {
        "X-Powered-By": {
            "PHP": r"PHP/[\d.]+",
            "ASP.NET": r"ASP\.NET",
            "Express": r"Express",
            "Next.js": r"Next\.js",
            "Kestrel": r"Kestrel",
        },
        "Server": {
            "Apache": r"Apache/?[\d.]*",
            "Nginx": r"nginx/?[\d.]*",
            "IIS": r"Microsoft-IIS/?[\d.]*",
            "LiteSpeed": r"LiteSpeed",
            "Cloudflare": r"cloudflare",
            "AmazonS3": r"AmazonS3",
            "Caddy": r"Caddy",
            "Gunicorn": r"gunicorn",
            "Cowboy": r"Cowboy",
            "Tengine": r"Tengine",
            "OpenResty": r"openresty",
        },
        "X-AspNet-Version": {
            "ASP.NET": r"[\d.]+",
        },
        "X-Generator": {
            "WordPress": r"WordPress[\s\d.]*",
            "Drupal": r"Drupal[\s\d.]*",
            "Joomla": r"Joomla[\s\d.]*",
        },
    },
    "cookies": {
        "PHPSESSID": "PHP",
        "ASP.NET_SessionId": "ASP.NET",
        "JSESSIONID": "Java",
        "connect.sid": "Node.js/Express",
        "laravel_session": "Laravel",
        "XSRF-TOKEN": "Angular/Laravel",
        "_csrf": "Express CSRF",
        "rack.session": "Ruby/Rack",
        "django_session": "Django",
        "csrftoken": "Django",
        "ci_session": "CodeIgniter",
        "wp-settings": "WordPress",
        "Drupal.visitor": "Drupal",
        "_gh_sess": "GitHub",
        "ARRAffinity": "Azure",
        "AWSALB": "AWS ALB",
        "AWSALBCORS": "AWS ALB (CORS)",
    },
    "body": {
        "WordPress": [r"wp-content/", r"wp-includes/", r"wp-json"],
        "Drupal": [r"Drupal", r"sites/default/files", r"drupal\.js"],
        "Joomla": [r"/media/jui/", r"Joomla!", r"/components/com_"],
        "React": [r"react\.production\.min\.js", r"__NEXT_DATA__", r"_reactRoot"],
        "Vue.js": [r"vue\.min\.js", r"vue\.runtime", r"__vue__"],
        "Angular": [r"angular\.min\.js", r"ng-version", r"ng-app"],
        "jQuery": [r"jquery[\-.][\d.]+\.min\.js", r"jquery\.min\.js"],
        "Bootstrap": [r"bootstrap\.min\.(css|js)", r"bootstrap[\-.][\d.]+"],
        "Cloudflare": [r"cdnjs\.cloudflare\.com", r"cf-ray"],
        "Google Analytics": [r"google-analytics\.com", r"googletagmanager\.com", r"gtag/js"],
        "Google Tag Manager": [r"googletagmanager\.com/gtm\.js"],
        "Hotjar": [r"static\.hotjar\.com"],
        "Segment": [r"cdn\.segment\.com"],
    },
}


# =============================================================================
# GOOGLE DORK TEMPLATES (40+)
# =============================================================================

GOOGLE_DORK_TEMPLATES = [
    'site:{target} filetype:pdf',
    'site:{target} filetype:doc OR filetype:docx',
    'site:{target} filetype:xls OR filetype:xlsx',
    'site:{target} filetype:ppt OR filetype:pptx',
    'site:{target} filetype:sql',
    'site:{target} filetype:log',
    'site:{target} filetype:bak',
    'site:{target} filetype:conf OR filetype:cfg',
    'site:{target} filetype:env',
    'site:{target} filetype:xml',
    'site:{target} filetype:json',
    'site:{target} filetype:yml OR filetype:yaml',
    'site:{target} filetype:ini',
    'site:{target} filetype:txt "password"',
    'site:{target} filetype:php',
    'site:{target} inurl:admin',
    'site:{target} inurl:login',
    'site:{target} inurl:dashboard',
    'site:{target} inurl:api',
    'site:{target} inurl:config',
    'site:{target} inurl:setup',
    'site:{target} inurl:install',
    'site:{target} inurl:wp-admin',
    'site:{target} inurl:wp-content',
    'site:{target} inurl:phpinfo',
    'site:{target} intitle:"index of"',
    'site:{target} intitle:"dashboard"',
    'site:{target} intitle:"admin panel"',
    'site:{target} intext:"sql syntax near"',
    'site:{target} intext:"error in your SQL syntax"',
    'site:{target} intext:"mysql_fetch_array"',
    'site:{target} intext:"Warning: mysql"',
    'site:{target} intext:"supplied argument is not a valid"',
    'site:{target} intext:"server at" intext:"port"',
    'site:{target} ext:asp OR ext:aspx',
    'site:{target} ext:jsp OR ext:jspx',
    'site:{target} "Index of /" +.htaccess',
    'site:{target} "Index of /" +passwd',
    'site:{target} "Index of /" +.git',
    'site:{target} inurl:"/wp-content/uploads"',
    'site:{target} inurl:"/phpMyAdmin/"',
    'site:{target} intext:"Powered by" inurl:"/readme.html"',
    'site:{target} inurl:".git" intitle:"Index of"',
    'site:{target} "Apache/2" "server at"',
    'site:{target} inurl:"/server-status"',
    'site:{target} inurl:"/server-info"',
    'site:{target} inurl:"/.env" intitle:"Index of"',
]


# =============================================================================
# SHODAN QUERY TEMPLATES
# =============================================================================

SHODAN_QUERY_TEMPLATES = [
    'hostname:"{target}"',
    'ssl.cert.subject.cn:"{target}"',
    'http.title:"{target}"',
    'org:"{target}"',
    'hostname:"{target}" port:22',
    'hostname:"{target}" port:3306',
    'hostname:"{target}" port:27017',
    'hostname:"{target}" product:"Apache"',
    'hostname:"{target}" product:"nginx"',
    'hostname:"{target}" http.status:401',
    'ssl:"{target}" 200',
]


# =============================================================================
# REDIRECT PARAMETERS (40+)
# =============================================================================

REDIRECT_PARAMS = [
    "url", "redirect", "redirect_url", "redirect_uri", "return", "return_url",
    "return_to", "rurl", "next", "next_url", "dest", "destination", "redir",
    "redirect_to", "out", "view", "to", "target", "link", "goto", "go",
    "returnTo", "return_path", "returnUrl", "r_url", "continue", "forward",
    "forward_url", "location", "path", "data", "reference", "site", "html",
    "val", "validate", "domain", "callback", "checkout_url", "login_url",
    "image_url", "return_page", "feed", "host", "port", "navigate",
]


# =============================================================================
# INFO DISCLOSURE PATHS (100+)
# =============================================================================

INFO_DISCLOSURE_PATHS = [
    "/.git/HEAD",
    "/.git/config",
    "/.svn/entries",
    "/.svn/wc.db",
    "/.hg/store/00changelog.i",
    "/.bzr/README",
    "/.DS_Store",
    "/server-status",
    "/server-info",
    "/phpinfo.php",
    "/info.php",
    "/test.php",
    "/php_info.php",
    "/i.php",
    "/.env",
    "/.env.bak",
    "/.env.local",
    "/.env.production",
    "/.env.development",
    "/wp-config.php.bak",
    "/web.config",
    "/crossdomain.xml",
    "/clientaccesspolicy.xml",
    "/elmah.axd",
    "/trace.axd",
    "/robots.txt",
    "/sitemap.xml",
    "/humans.txt",
    "/security.txt",
    "/.well-known/security.txt",
    "/.htaccess",
    "/.htpasswd",
    "/nginx.conf",
    "/httpd.conf",
    "/docker-compose.yml",
    "/Dockerfile",
    "/Makefile",
    "/Gruntfile.js",
    "/Gulpfile.js",
    "/package.json",
    "/package-lock.json",
    "/yarn.lock",
    "/composer.json",
    "/composer.lock",
    "/Gemfile",
    "/Gemfile.lock",
    "/requirements.txt",
    "/Pipfile",
    "/Pipfile.lock",
    "/bower.json",
    "/tsconfig.json",
    "/webpack.config.js",
    "/.babelrc",
    "/.eslintrc",
    "/.prettierrc",
    "/config.yml",
    "/config.yaml",
    "/config.json",
    "/config.xml",
    "/config.ini",
    "/settings.py",
    "/settings.json",
    "/database.yml",
    "/credentials.yml",
    "/secrets.yml",
    "/application.yml",
    "/application.properties",
    "/.aws/credentials",
    "/.ssh/id_rsa",
    "/.ssh/id_rsa.pub",
    "/.bash_history",
    "/.zsh_history",
    "/error.log",
    "/access.log",
    "/debug.log",
    "/error_log",
    "/access_log",
    "/app.log",
    "/application.log",
    "/.idea/workspace.xml",
    "/.vscode/settings.json",
    "/.vscode/launch.json",
    "/WEB-INF/web.xml",
    "/WEB-INF/classes/",
    "/META-INF/MANIFEST.MF",
    "/MANIFEST.MF",
    "/api/swagger.json",
    "/api/swagger.yaml",
    "/swagger.json",
    "/swagger.yaml",
    "/openapi.json",
    "/openapi.yaml",
    "/api-docs",
    "/graphql",
    "/graphiql",
    "/altair",
    "/playground",
    "/_debug/",
    "/__debug__/",
    "/debug/default/view",
    "/actuator",
    "/actuator/health",
    "/actuator/env",
    "/actuator/info",
    "/actuator/mappings",
    "/actuator/beans",
    "/actuator/configprops",
    "/actuator/threaddump",
    "/actuator/heapdump",
    "/metrics",
    "/health",
    "/healthcheck",
    "/status",
]


# =============================================================================
# SENSITIVE FILE PATHS (500+ entries)
# =============================================================================

SENSITIVE_FILE_PATHS = [
    # Version Control
    ".git/HEAD",
    ".git/config",
    ".git/index",
    ".git/logs/HEAD",
    ".git/refs/heads/master",
    ".git/refs/heads/main",
    ".git/packed-refs",
    ".git/objects/info/packs",
    ".gitignore",
    ".gitattributes",
    ".gitmodules",
    ".svn/entries",
    ".svn/wc.db",
    ".svn/all-wcprops",
    ".hg/store/00changelog.i",
    ".hg/hgrc",
    ".bzr/README",
    ".bzr/branch/branch.conf",

    # Environment & Config Files
    ".env",
    ".env.bak",
    ".env.backup",
    ".env.dev",
    ".env.development",
    ".env.local",
    ".env.prod",
    ".env.production",
    ".env.staging",
    ".env.test",
    ".env.example",
    ".env.sample",
    ".env.old",
    ".env.save",
    ".env.swp",
    ".env.tmp",
    "env.js",
    "env.json",
    "env.yaml",
    "env.yml",
    ".flaskenv",
    ".envrc",
    "dotenv",

    # Web Server Config
    ".htaccess",
    ".htpasswd",
    "nginx.conf",
    "nginx/nginx.conf",
    "conf/nginx.conf",
    "httpd.conf",
    "apache2.conf",
    "lighttpd.conf",
    "web.config",
    "Web.config",
    ".user.ini",
    "php.ini",
    ".php_cs",
    ".phpunit.result.cache",

    # Application Config
    "config.php",
    "config.inc.php",
    "config.old.php",
    "config.bak.php",
    "configuration.php",
    "settings.php",
    "settings.py",
    "settings.pyc",
    "local_settings.py",
    "config.py",
    "config.rb",
    "config.js",
    "config.json",
    "config.yml",
    "config.yaml",
    "config.xml",
    "config.ini",
    "config.toml",
    "app.config",
    "app.yaml",
    "app.yml",
    "app.json",
    "application.yml",
    "application.yaml",
    "application.properties",
    "application-dev.yml",
    "application-prod.yml",
    "appsettings.json",
    "appsettings.Development.json",
    "appsettings.Production.json",

    # Database Files
    "database.yml",
    "database.json",
    "database.sqlite",
    "database.sqlite3",
    "database.db",
    "db.sqlite",
    "db.sqlite3",
    "data.sql",
    "dump.sql",
    "backup.sql",
    "database.sql",
    "db.sql",
    "mysql.sql",
    "db_backup.sql",
    "site.db",
    "data.db",
    "users.db",

    # Credentials & Secrets
    "credentials.json",
    "credentials.yml",
    "credentials.xml",
    "secrets.json",
    "secrets.yml",
    "secrets.yaml",
    "secret_key_base",
    "master.key",
    "encryption.key",
    "api_keys.json",
    "api_keys.yml",
    "service-account.json",
    "google-credentials.json",
    "firebase-adminsdk.json",
    "firebase.json",
    "keystore.jks",
    "truststore.jks",
    ".npmrc",
    ".pypirc",
    ".netrc",
    ".pgpass",
    ".my.cnf",
    ".dockercfg",
    ".docker/config.json",

    # AWS
    ".aws/credentials",
    ".aws/config",
    "aws.yml",
    "s3cfg",

    # SSH & Keys
    ".ssh/id_rsa",
    ".ssh/id_rsa.pub",
    ".ssh/id_dsa",
    ".ssh/id_ecdsa",
    ".ssh/id_ed25519",
    ".ssh/authorized_keys",
    ".ssh/known_hosts",
    ".ssh/config",
    "id_rsa",
    "id_dsa",
    "server.key",
    "server.pem",
    "private.key",
    "private.pem",
    "privatekey.pem",
    "ssl/private.key",
    "ssl/server.key",
    "cert.pem",
    "certificate.pem",

    # Backup Files
    "backup.zip",
    "backup.tar.gz",
    "backup.tar",
    "backup.gz",
    "backup.rar",
    "site.zip",
    "site.tar.gz",
    "www.zip",
    "www.tar.gz",
    "html.zip",
    "public.zip",
    "htdocs.zip",
    "web.zip",
    "source.zip",
    "src.zip",
    "code.zip",
    "old.zip",
    "archive.zip",
    "files.zip",
    "dump.zip",
    "db.zip",
    "mysql.zip",
    "sql.zip",
    "data.zip",
    "1.zip",
    "2.zip",
    "temp.zip",
    "test.zip",
    "bak.zip",
    "backup.bak",
    "index.bak",
    "index.php.bak",
    "index.html.bak",
    "config.bak",

    # WordPress
    "wp-config.php",
    "wp-config.php.bak",
    "wp-config.php.old",
    "wp-config.php.save",
    "wp-config.php.swp",
    "wp-config.php.txt",
    "wp-config.bak",
    "wp-config.old",
    "wp-config.txt",
    "wp-login.php",
    "wp-admin/",
    "wp-content/debug.log",
    "wp-content/uploads/",
    "wp-includes/",
    "xmlrpc.php",
    "wp-cron.php",
    "wp-json/wp/v2/users",

    # CMS & Frameworks
    "administrator/",
    "admin/",
    "admin.php",
    "admin/login",
    "admin/config.php",
    "administrator/manifests/files/joomla.xml",
    "sites/default/settings.php",
    "sites/default/files/",
    "CHANGELOG.txt",
    "INSTALL.txt",
    "UPGRADE.txt",
    "LICENSE.txt",
    "README.txt",
    "readme.html",
    "RELEASE_NOTES.txt",

    # Log Files
    "error.log",
    "error_log",
    "access.log",
    "access_log",
    "debug.log",
    "debug_log",
    "app.log",
    "application.log",
    "server.log",
    "system.log",
    "syslog",
    "production.log",
    "development.log",
    "laravel.log",
    "storage/logs/laravel.log",
    "var/log/apache2/error.log",
    "var/log/nginx/error.log",
    "logs/error.log",
    "logs/access.log",
    "tmp/logs/error.log",
    "log/development.log",
    "log/production.log",
    "catalina.out",
    "tomcat.log",

    # PHP Specific
    "phpinfo.php",
    "info.php",
    "test.php",
    "php_info.php",
    "i.php",
    "pi.php",
    "p.php",
    "php.php",
    "phpversion.php",
    "adminer.php",
    "phpmyadmin/",
    "pma/",
    "myadmin/",
    "mysql/",
    "mysqlmanager/",
    "sqlmanager/",
    "phppgadmin/",
    "pgadmin/",

    # Java/Spring
    "WEB-INF/web.xml",
    "WEB-INF/applicationContext.xml",
    "WEB-INF/classes/",
    "META-INF/MANIFEST.MF",
    "META-INF/context.xml",
    "META-INF/maven/",
    "actuator/",
    "actuator/env",
    "actuator/health",
    "actuator/info",
    "actuator/mappings",
    "actuator/beans",
    "actuator/configprops",
    "actuator/threaddump",
    "actuator/heapdump",
    "actuator/loggers",
    "actuator/metrics",

    # Node.js
    "package.json",
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "node_modules/.package-lock.json",
    ".npmrc",
    ".yarnrc",
    ".yarnrc.yml",
    "tsconfig.json",
    "webpack.config.js",
    "next.config.js",
    "nuxt.config.js",
    "vue.config.js",
    "angular.json",
    ".babelrc",
    ".babelrc.js",
    "babel.config.js",
    "jest.config.js",
    "pm2.json",
    "ecosystem.config.js",

    # Python
    "requirements.txt",
    "Pipfile",
    "Pipfile.lock",
    "poetry.lock",
    "pyproject.toml",
    "setup.py",
    "setup.cfg",
    "tox.ini",
    "pytest.ini",
    "manage.py",
    "wsgi.py",
    "asgi.py",
    "celery.py",
    "alembic.ini",
    "migrations/",

    # Ruby
    "Gemfile",
    "Gemfile.lock",
    "Rakefile",
    "config/database.yml",
    "config/secrets.yml",
    "config/master.key",
    "config/credentials.yml.enc",
    "config/initializers/secret_token.rb",
    "config/environments/production.rb",
    "config/environments/development.rb",

    # Docker & CI/CD
    "Dockerfile",
    "docker-compose.yml",
    "docker-compose.yaml",
    "docker-compose.dev.yml",
    "docker-compose.prod.yml",
    ".dockerignore",
    "Vagrantfile",
    "Jenkinsfile",
    ".travis.yml",
    ".circleci/config.yml",
    ".github/workflows/",
    ".gitlab-ci.yml",
    "bitbucket-pipelines.yml",
    "azure-pipelines.yml",
    "Procfile",
    "heroku.yml",
    "app.json",
    "now.json",
    "vercel.json",
    "netlify.toml",
    "fly.toml",
    "render.yaml",

    # IDE & Editor
    ".idea/workspace.xml",
    ".idea/modules.xml",
    ".idea/vcs.xml",
    ".idea/misc.xml",
    ".vscode/settings.json",
    ".vscode/launch.json",
    ".vscode/tasks.json",
    ".editorconfig",
    ".project",
    ".classpath",
    ".settings/",
    "nbproject/",
    "*.sublime-project",
    "*.sublime-workspace",

    # Miscellaneous
    ".DS_Store",
    "Thumbs.db",
    "desktop.ini",
    ".directory",
    "crossdomain.xml",
    "clientaccesspolicy.xml",
    "security.txt",
    ".well-known/security.txt",
    "humans.txt",
    "ads.txt",
    "app-ads.txt",
    "manifest.json",
    "browserconfig.xml",
    "apple-app-site-association",
    ".well-known/apple-app-site-association",
    "assetlinks.json",
    ".well-known/assetlinks.json",

    # API Documentation
    "swagger.json",
    "swagger.yaml",
    "swagger-ui.html",
    "api-docs/",
    "openapi.json",
    "openapi.yaml",
    "graphql",
    "graphiql",
    "altair",
    "playground",
    "api/v1/",
    "api/v2/",
    "api/docs",
    "api/explorer",
    "_api/",
    "rest/api/",

    # Debug & Status
    "debug/",
    "__debug__/",
    "debug/default/view",
    "console/",
    "trace.axd",
    "elmah.axd",
    "health",
    "healthcheck",
    "health-check",
    "status",
    "ping",
    "metrics",
    "prometheus/metrics",
    "monitoring",
    "_status",
    "version",
    "build-info",
    "server-status",
    "server-info",

    # Terraform & IaC
    "terraform.tfstate",
    "terraform.tfstate.backup",
    "terraform.tfvars",
    "variables.tf",
    "main.tf",
    "outputs.tf",
    ".terraform/",
    "pulumi.yaml",
    "ansible.cfg",
    "playbook.yml",
    "inventory",
    "vault.yml",

    # Mobile
    "Info.plist",
    "GoogleService-Info.plist",
    "google-services.json",
    "AndroidManifest.xml",
    "proguard-rules.pro",
    "local.properties",
    "gradle.properties",
    "build.gradle",

    # Temp & Swap Files
    "tmp/",
    "temp/",
    "cache/",
    ".cache/",
    "*.swp",
    "*.swo",
    "*~",
    "*.tmp",
    "*.bak",
    "*.old",
    "*.orig",
    "*.save",
    "*.rej",
    "#*#",

    "backup/db.sql",
    "backup/site.sql",
    "backup/data.sql",
    "backups/latest.sql",
    "backups/daily.sql",
    "old/index.php",
    "old/config.php",
    "bak/config.php",
    "copy/config.php",
    "temp/config.php",
    "save/config.php",
    "var/log/syslog",
    "var/log/messages",
    "var/log/auth.log",
    "var/log/secure",
    "var/log/mail.log",
    "var/log/cron.log",
    "var/log/kern.log",
    "var/log/boot.log",
    "var/log/dmesg",
    "var/log/wtmp",
    "var/log/btmp",
    "var/log/lastlog",
    "var/log/faillog",
    "etc/passwd",
    "etc/shadow",
    "etc/hosts",
    "etc/hostname",
    "etc/resolv.conf",
    "etc/nginx/nginx.conf",
    "etc/apache2/apache2.conf",
    "etc/httpd/httpd.conf",
    "etc/mysql/my.cnf",
    "etc/postgresql/pg_hba.conf",
    "etc/redis/redis.conf",
    "etc/mongod.conf",
    "etc/ssh/sshd_config",
    "etc/ssl/private/",
    "etc/letsencrypt/",
    "etc/crontab",
    "etc/sudoers",
    "etc/profile",
    "etc/environment",
    ".github/workflows/deploy.yml",
    ".github/workflows/build.yml",
    ".github/workflows/test.yml",
    ".github/workflows/ci.yml",
    ".github/workflows/cd.yml",
    ".github/workflows/release.yml",
    "Makefile",
    "makefile",
    "GNUmakefile",
    "Justfile",
    "Taskfile.yml",
    "k8s/deployment.yaml",
    "k8s/service.yaml",
    "k8s/ingress.yaml",
    "k8s/secrets.yaml",
    "k8s/configmap.yaml",
    "charts/values.yaml",
    "helmfile.yaml",
    "skaffold.yaml",
    "kustomization.yaml",
    "next.config.mjs",
    "vite.config.js",
    "vite.config.ts",
    "rollup.config.js",
    "esbuild.config.js",
    "turbo.json",
    "lerna.json",
    "rush.json",
    "pnpm-workspace.yaml",
    "nx.json",
    "deno.json",
    "bun.lockb",
    "artisan",
    "bootstrap/cache/",
    "storage/framework/sessions/",
    "storage/app/",
    "vendor/autoload.php",
    "composer.phar",
    "admin/backup",
    "admin/export",
    "admin/import",
    "admin/logs",
    "admin/debug",
    "admin/phpinfo",
    "admin/users",
    "admin/settings",
    "admin/database",
    "admin/console",
    "panel/",
    "panel/login",
    "dashboard/login",
    "manage/",
    "management/",
    "siteadmin/",
    "webadmin/",
    "system/",
    "system/admin",
]


# =============================================================================
# WAF SIGNATURES DATABASE (10+ WAFs)
# =============================================================================

WAF_SIGNATURES = {
    "Cloudflare": {
        "headers": ["cf-ray", "cf-cache-status", "cf-request-id"],
        "cookies": ["__cfduid", "__cf_bm", "cf_clearance"],
        "body_patterns": ["Attention Required! | Cloudflare", "cloudflare-nginx", "cf-ray"],
        "status_codes": [403, 503],
    },
    "AWS WAF": {
        "headers": ["x-amzn-requestid", "x-amz-cf-id", "x-amz-id-2"],
        "cookies": ["awsalb", "awsalbcors"],
        "body_patterns": ["<html><head><title>403 Forbidden</title>", "Request blocked"],
        "status_codes": [403],
    },
    "Akamai": {
        "headers": ["x-akamai-transformed", "akamai-grn", "x-akamai-session-info"],
        "cookies": ["akamai_", "ak_bmsc", "bm_sz"],
        "body_patterns": ["Access Denied", "Reference #", "akamaighost"],
        "status_codes": [403],
    },
    "Imperva/Incapsula": {
        "headers": ["x-iinfo", "x-cdn"],
        "cookies": ["visid_incap_", "incap_ses_", "nlbi_"],
        "body_patterns": ["Incapsula incident ID", "Request unsuccessful", "powered by Incapsula"],
        "status_codes": [403],
    },
    "F5 BIG-IP ASM": {
        "headers": ["x-wa-info", "x-cnection"],
        "cookies": ["TS", "BIGipServer", "f5_cspm"],
        "body_patterns": ["The requested URL was rejected", "Please consult with your administrator"],
        "status_codes": [403],
    },
    "Sucuri": {
        "headers": ["x-sucuri-id", "x-sucuri-cache"],
        "cookies": ["sucuri_cloudproxy_uuid"],
        "body_patterns": ["Access Denied - Sucuri Website Firewall", "Sucuri WebSite Firewall", "cloudproxy"],
        "status_codes": [403],
    },
    "ModSecurity": {
        "headers": ["server"],
        "cookies": [],
        "body_patterns": ["ModSecurity", "Mod_Security", "NOYB", "This error was generated by Mod_Security"],
        "status_codes": [403, 406],
    },
    "Barracuda": {
        "headers": ["barra_counter_session"],
        "cookies": ["barra_counter_session", "BNI__BARRACUDA_LB_COOKIE"],
        "body_patterns": ["Barracuda Web Application Firewall"],
        "status_codes": [403],
    },
    "Fortinet/FortiWeb": {
        "headers": ["fortiwafsid"],
        "cookies": ["FORTIWAFSID"],
        "body_patterns": ["FortiWeb", ".fgd_icon", "web page blocked"],
        "status_codes": [403],
    },
    "Citrix NetScaler": {
        "headers": ["cneonction", "nncoection", "x-nsc-"],
        "cookies": ["citrix_ns_id", "NSC_"],
        "body_patterns": ["ns_af=", "citrix", "NetScaler"],
        "status_codes": [403],
    },
    "DenyAll": {
        "headers": [],
        "cookies": ["sessioncookie"],
        "body_patterns": ["Condition Intercepted", "denyall"],
        "status_codes": [403],
    },
    "Wordfence": {
        "headers": [],
        "cookies": ["wfvt_", "wordfence_verifiedHuman"],
        "body_patterns": ["Generated by Wordfence", "This response was generated by Wordfence"],
        "status_codes": [403, 503],
    },
    "Comodo WAF": {
        "headers": [],
        "cookies": [],
        "body_patterns": ["Protected by COMODO WAF"],
        "status_codes": [403],
    },
    "StackPath": {
        "headers": ["x-sp-url", "x-sp-waf-request-id"],
        "cookies": [],
        "body_patterns": ["StackPath", "You performed an action that triggered"],
        "status_codes": [403],
    },
    "Edgecast/Verizon": {
        "headers": ["x-ec-custom-error"],
        "cookies": [],
        "body_patterns": ["Please verify you are a human", "Access Denied"],
        "status_codes": [403],
    },
}


# =============================================================================
# COMMON VULNERABLE PARAMETERS (200+)
# =============================================================================

COMMON_PARAMS = [
    # SQL Injection
    "id", "Id", "ID", "uid", "userid", "user_id", "pid", "page_id",
    "cat", "catid", "category", "category_id", "item", "item_id",
    "product", "product_id", "order", "order_id", "num", "number",
    "article", "article_id", "news", "news_id", "thread", "post",
    "comment", "comment_id", "msg", "message_id", "report", "report_id",
    "select", "table", "from", "where", "query", "q", "search",
    "keyword", "keywords", "filter", "sort", "column", "field",
    "limit", "offset", "start", "end", "begin", "range",

    # XSS
    "name", "username", "user", "email", "mail", "pass", "password",
    "input", "output", "content", "text", "body", "title", "desc",
    "description", "comment", "feedback", "review", "note", "notes",
    "message", "msg", "subject", "headline", "summary", "bio",
    "about", "info", "label", "tag", "tags", "value", "val",
    "data", "payload", "html", "code", "script", "style",
    "class", "className", "type", "alt", "src", "href", "action",
    "onload", "onerror", "onclick", "template", "render",

    # SSRF
    "url", "uri", "path", "src", "source", "dest", "destination",
    "redirect", "redirect_url", "redirect_uri", "return_url", "next",
    "rurl", "target", "link", "site", "host", "domain", "feed",
    "img", "image", "image_url", "icon", "icon_url", "avatar",
    "avatar_url", "photo", "photo_url", "picture", "picture_url",
    "load", "fetch", "request", "proxy", "callback", "api",
    "api_url", "endpoint", "webhook", "webhook_url", "ping",
    "file", "filename", "file_url", "attachment", "download",

    # File Inclusion (LFI/RFI)
    "file", "filename", "filepath", "path", "folder", "dir",
    "directory", "doc", "document", "root", "pg", "page",
    "include", "inc", "require", "read", "load", "open",
    "view", "show", "display", "content", "template", "tpl",
    "module", "mod", "plugin", "ext", "extension", "theme",
    "layout", "lang", "language", "locale", "loc",

    # Command Injection
    "cmd", "command", "exec", "execute", "run", "system",
    "ping", "query", "jump", "code", "reg", "do", "func",
    "function", "option", "options", "process", "step",
    "read", "write", "feature", "exe", "module", "payload",
    "daemon", "upload", "dir", "download", "log", "ip",
    "cli", "hostname", "port", "dns", "timeout",

    # Authentication/Session
    "token", "auth", "auth_token", "access_token", "refresh_token",
    "session", "session_id", "sid", "jwt", "api_key", "apikey",
    "key", "secret", "client_id", "client_secret", "grant_type",
    "scope", "state", "nonce", "code", "ticket",

    # IDOR
    "account", "account_id", "acct", "profile", "profile_id",
    "admin", "admin_id", "role", "role_id", "group", "group_id",
    "org", "org_id", "team", "team_id", "project", "project_id",
    "workspace", "workspace_id", "tenant", "tenant_id",
    "customer", "customer_id", "invoice", "invoice_id",
    "payment", "payment_id", "transaction", "transaction_id",
]


# =============================================================================
# SUBDOMAIN WORDLIST (2000 inline entries)
# =============================================================================

SUBDOMAIN_WORDLIST = [
    "www",
    "mail",
    "ftp",
    "smtp",
    "pop",
    "pop3",
    "imap",
    "ns1",
    "ns2",
    "ns3",
    "ns4",
    "dns",
    "dns1",
    "dns2",
    "mx",
    "mx1",
    "mx2",
    "webmail",
    "email",
    "admin",
    "administrator",
    "api",
    "app",
    "apps",
    "auth",
    "dev",
    "dev1",
    "dev2",
    "dev3",
    "development",
    "staging",
    "stage",
    "stg",
    "test",
    "testing",
    "test1",
    "test2",
    "test3",
    "qa",
    "uat",
    "sandbox",
    "demo",
    "beta",
    "alpha",
    "preview",
    "pre",
    "preprod",
    "pre-prod",
    "prod",
    "production",
    "live",
    "portal",
    "my",
    "account",
    "accounts",
    "login",
    "signin",
    "signup",
    "register",
    "sso",
    "auth0",
    "identity",
    "id",
    "oauth",
    "secure",
    "security",
    "vpn",
    "remote",
    "gateway",
    "gw",
    "proxy",
    "nat",
    "firewall",
    "fw",
    "router",
    "switch",
    "hub",
    "bridge",
    "tunnel",
    "connect",
    "access",
    "web",
    "web1",
    "web2",
    "web3",
    "www1",
    "www2",
    "www3",
    "site",
    "sites",
    "blog",
    "blogs",
    "news",
    "forum",
    "forums",
    "community",
    "social",
    "wiki",
    "docs",
    "doc",
    "documentation",
    "help",
    "helpdesk",
    "support",
    "kb",
    "knowledgebase",
    "faq",
    "info",
    "about",
    "contact",
    "feedback",
    "cdn",
    "cdn1",
    "cdn2",
    "cdn3",
    "static",
    "assets",
    "img",
    "images",
    "image",
    "media",
    "video",
    "videos",
    "stream",
    "streaming",
    "files",
    "file",
    "upload",
    "uploads",
    "download",
    "downloads",
    "content",
    "cloud",
    "aws",
    "azure",
    "gcp",
    "s3",
    "storage",
    "bucket",
    "blob",
    "backup",
    "backups",
    "bak",
    "archive",
    "archives",
    "old",
    "legacy",
    "db",
    "database",
    "mysql",
    "postgres",
    "postgresql",
    "mongo",
    "mongodb",
    "redis",
    "memcached",
    "elastic",
    "elasticsearch",
    "solr",
    "cassandra",
    "sql",
    "mssql",
    "oracle",
    "mariadb",
    "couchdb",
    "dynamodb",
    "influxdb",
    "shop",
    "store",
    "ecommerce",
    "cart",
    "checkout",
    "payment",
    "payments",
    "pay",
    "billing",
    "invoice",
    "orders",
    "order",
    "catalog",
    "products",
    "crm",
    "erp",
    "hrm",
    "hr",
    "finance",
    "accounting",
    "inventory",
    "marketing",
    "analytics",
    "tracking",
    "stats",
    "statistics",
    "metrics",
    "monitor",
    "monitoring",
    "status",
    "health",
    "healthcheck",
    "nagios",
    "zabbix",
    "grafana",
    "prometheus",
    "kibana",
    "datadog",
    "splunk",
    "jenkins",
    "ci",
    "cd",
    "build",
    "builds",
    "deploy",
    "deployment",
    "releases",
    "release",
    "artifacts",
    "nexus",
    "artifactory",
    "docker",
    "registry",
    "container",
    "containers",
    "k8s",
    "kubernetes",
    "cluster",
    "git",
    "github",
    "gitlab",
    "bitbucket",
    "svn",
    "repo",
    "repos",
    "repository",
    "code",
    "source",
    "src",
    "vcs",
    "scm",
    "jira",
    "confluence",
    "atlassian",
    "trello",
    "asana",
    "notion",
    "slack",
    "teams",
    "chat",
    "im",
    "irc",
    "xmpp",
    "jabber",
    "voip",
    "sip",
    "pbx",
    "asterisk",
    "phone",
    "tel",
    "telephone",
    "ldap",
    "ad",
    "activedirectory",
    "dc",
    "dc1",
    "dc2",
    "pdc",
    "exchange",
    "owa",
    "outlook",
    "o365",
    "office",
    "office365",
    "sharepoint",
    "onedrive",
    "skype",
    "internal",
    "intranet",
    "extranet",
    "corp",
    "corporate",
    "private",
    "public",
    "external",
    "edge",
    "dmz",
    "perimeter",
    "report",
    "reports",
    "reporting",
    "dashboard",
    "dashboards",
    "panel",
    "console",
    "terminal",
    "shell",
    "ssh",
    "telnet",
    "rdp",
    "log",
    "logs",
    "logging",
    "syslog",
    "audit",
    "events",
    "event",
    "alert",
    "alerts",
    "notification",
    "notifications",
    "notify",
    "search",
    "lucene",
    "find",
    "lookup",
    "map",
    "maps",
    "geo",
    "gis",
    "location",
    "places",
    "calendar",
    "cal",
    "schedule",
    "booking",
    "reservation",
    "appointments",
    "project",
    "projects",
    "task",
    "tasks",
    "ticket",
    "tickets",
    "issue",
    "issues",
    "bug",
    "bugs",
    "tracker",
    "track",
    "survey",
    "surveys",
    "poll",
    "polls",
    "vote",
    "voting",
    "game",
    "games",
    "gaming",
    "play",
    "player",
    "lobby",
    "mobile",
    "m",
    "mobi",
    "wap",
    "app1",
    "app2",
    "application",
    "service",
    "services",
    "svc",
    "microservice",
    "microservices",
    "rest",
    "restapi",
    "graphql",
    "grpc",
    "soap",
    "wsdl",
    "webhook",
    "webhooks",
    "hook",
    "hooks",
    "callback",
    "callbacks",
    "push",
    "pull",
    "sync",
    "async",
    "queue",
    "mq",
    "rabbitmq",
    "kafka",
    "amqp",
    "mqtt",
    "nats",
    "zeromq",
    "cache",
    "varnish",
    "nginx",
    "apache",
    "haproxy",
    "lb",
    "loadbalancer",
    "load-balancer",
    "balancer",
    "reverse-proxy",
    "cert",
    "certs",
    "certificate",
    "ssl",
    "tls",
    "pki",
    "ca",
    "vpn1",
    "vpn2",
    "openvpn",
    "wireguard",
    "ipsec",
    "wifi",
    "wlan",
    "wireless",
    "lan",
    "wan",
    "network",
    "noc",
    "datacenter",
    "dc3",
    "colo",
    "colocation",
    "vendor",
    "vendors",
    "partner",
    "partners",
    "supplier",
    "suppliers",
    "client",
    "clients",
    "customer",
    "customers",
    "user",
    "users",
    "member",
    "members",
    "subscriber",
    "subscribers",
    "new",
    "v1",
    "v2",
    "v3",
    "v4",
    "version",
    "temp",
    "tmp",
    "scratch",
    "lab",
    "labs",
    "research",
    "data",
    "bigdata",
    "hadoop",
    "spark",
    "ml",
    "ai",
    "learn",
    "learning",
    "training",
    "education",
    "edu",
    "school",
    "library",
    "lib",
    "resources",
    "resource",
    "asset",
    "config",
    "configuration",
    "setup",
    "install",
    "installer",
    "update",
    "updates",
    "upgrade",
    "patch",
    "hotfix",
    "api1",
    "api2",
    "api3",
    "api-v1",
    "api-v2",
    "api-internal",
    "admin1",
    "admin2",
    "cpanel",
    "plesk",
    "whm",
    "webmin",
    "phpmyadmin",
    "pma",
    "adminer",
    "pgadmin",
    "dba",
    "backup1",
    "backup2",
    "dr",
    "disaster-recovery",
    "failover",
    "primary",
    "secondary",
    "master",
    "slave",
    "replica",
    "node",
    "node1",
    "node2",
    "node3",
    "worker",
    "workers",
    "agent",
    "agents",
    "bot",
    "bots",
    "crawler",
    "spider",
    "cms",
    "wordpress",
    "wp",
    "drupal",
    "joomla",
    "magento",
    "typo3",
    "ghost",
    "strapi",
    "contentful",
    "mail1",
    "mail2",
    "mail3",
    "mailserver",
    "mailer",
    "postfix",
    "dovecot",
    "sendmail",
    "relay",
    "smtp1",
    "smtp2",
    "ns5",
    "ns6",
    "ns7",
    "ns8",
    "resolver",
    "recursive",
    "ntp",
    "time",
    "clock",
    "snmp",
    "trap",
    "radius",
    "tacacs",
    "aaa",
    "auth1",
    "auth2",
    "proxy1",
    "proxy2",
    "squid",
    "privoxy",
    "tor",
    "ads",
    "adserver",
    "advertising",
    "banner",
    "banners",
    "affiliate",
    "affiliates",
    "referral",
    "referrals",
    "pixel",
    "beacon",
    "tag",
    "tags",
    "seo",
    "sitemap",
    "rss",
    "feed",
    "atom",
    "print",
    "printer",
    "printers",
    "scan",
    "scanner",
    "cam",
    "camera",
    "cameras",
    "cctv",
    "surveillance",
    "iot",
    "device",
    "devices",
    "sensor",
    "sensors",
    "home",
    "server",
    "server1",
    "server2",
    "host",
    "host1",
    "win",
    "windows",
    "linux",
    "unix",
    "mac",
    "osx",
    "dev-api",
    "stg-api",
    "prod-api",
    "api-dev",
    "api-stg",
    "dev-app",
    "stg-app",
    "prod-app",
    "app-dev",
    "app-stg",
    "dev-web",
    "stg-web",
    "prod-web",
    "web-dev",
    "web-stg",
    "origin",
    "origin-www",
    "direct",
    "real",
    "autodiscover",
    "autoconfig",
    "wpad",
    "pac",
    "citrix",
    "ica",
    "xenapp",
    "xendesktop",
    "sap",
    "peoplesoft",
    "siebel",
    "salesforce",
    "sf",
    "hubspot",
    "marketo",
    "pardot",
    "zendesk",
    "freshdesk",
    "servicenow",
    "remedy",
    "okta",
    "ping",
    "onelogin",
    "duo",
    "aws1",
    "azure1",
    "gcp1",
    "cloud1",
    "cloud2",
    "s3-website",
    "cloudfront",
    "elasticbeanstalk",
    "heroku",
    "netlify",
    "vercel",
    "render",
    "fly",
    "git1",
    "git2",
    "svn1",
    "hg",
    "npm",
    "pip",
    "gem",
    "composer",
    "maven",
    "artifactory1",
    "nexus1",
    "sonatype",
    "vault",
    "secrets",
    "keystore",
    "hsm",
    "compliance",
    "audit1",
    "risk",
    "governance",
    "legal",
    "policy",
    "privacy",
    "terms",
    "careers",
    "jobs",
    "recruiting",
    "talent",
    "hire",
    "press",
    "pr",
    "media1",
    "communications",
    "investor",
    "investors",
    "ir",
    "stockholders",
    "sustainability",
    "csr",
    "esg",
    "green",
    "brand",
    "branding",
    "creative",
    "design",
    "ux",
    "ui",
    "prototype",
    "figma",
    "sketch",
    "spa",
    "pwa",
    "amp",
    "lite",
    "light",
    "fast",
    "turbo",
    "rocket",
    "speed",
    "perf",
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "g",
    "h",
    "i",
    "j",
    "k",
    "l",
    "m1",
    "n",
    "o",
    "p",
    "q",
    "r",
    "s",
    "t",
    "www-dev",
    "www-staging",
    "www-test",
    "www-beta",
    "api-gateway",
    "api-gateway-dev",
    "api-gateway-prod",
    "auth-api",
    "user-api",
    "data-api",
    "admin-api",
    "web-app",
    "mobile-api",
    "mobile-app",
    "mobile-web",
    "east",
    "west",
    "north",
    "south",
    "central",
    "us",
    "eu",
    "uk",
    "de",
    "fr",
    "jp",
    "cn",
    "au",
    "in",
    "us-east",
    "us-west",
    "eu-west",
    "eu-central",
    "ap-southeast",
    "zone1",
    "zone2",
    "zone3",
    "region1",
    "region2",
    "core",
    "platform",
    "engine",
    "runtime",
    "system",
    "exchange1",
    "trading",
    "market",
    "trade",
    "blockchain",
    "crypto",
    "bitcoin",
    "ethereum",
    "defi",
    "pay1",
    "wallet",
    "fintech",
    "banking",
    "insurance",
    "claims",
    "underwriting",
    "health1",
    "medical",
    "clinical",
    "patient",
    "ehr",
    "pharmacy",
    "rx",
    "laboratory",
    "diagnostic",
    "hotel",
    "travel",
    "booking1",
    "reservation1",
    "flight",
    "car",
    "auto",
    "vehicle",
    "fleet",
    "transport",
    "food",
    "delivery",
    "logistics",
    "shipping",
    "warehouse",
    "real-estate",
    "property",
    "listing",
    "rental",
    "education1",
    "lms",
    "course",
    "courses",
    "classroom",
    "exam",
    "quiz",
    "assessment",
    "grading",
    "music",
    "audio",
    "podcast",
    "radio",
    "fm",
    "tv",
    "broadcast",
    "channel",
    "live1",
    "vod",
    "photo",
    "gallery",
    "album",
    "portfolio",
    "ai1",
    "ml1",
    "deep-learning",
    "nlp",
    "cv",
    "robot",
    "automation",
    "rpa",
    "workflow",
    "erp1",
    "sap1",
    "dynamics",
    "netsuite",
    "helpdesk1",
    "servicedesk",
    "itsm",
    "itil",
    "cmdb",
    "asset1",
    "inventory1",
    "procurement",
    "bi",
    "tableau",
    "powerbi",
    "looker",
    "qlik",
    "etl",
    "pipeline",
    "airflow",
    "databricks",
    "lake",
    "warehouse1",
    "dwh",
    "mart",
    "nosql",
    "graph",
    "neo4j",
    "arangodb",
    "dgraph",
    "timeseries",
    "tsdb",
    "clickhouse",
    "druid",
    "cache1",
    "memcache",
    "redis1",
    "hazelcast",
    "session",
    "sessions",
    "token1",
    "tokens",
    "api-docs",
    "developer",
    "developers",
    "devportal",
    "marketplace",
    "market1",
    "exchange2",
    "addon",
    "addons",
    "plugin",
    "plugins",
    "extension",
    "theme",
    "themes",
    "template",
    "templates",
    "widget",
    "widgets",
    "component",
    "components",
    "micro",
    "nano",
    "mini",
    "macro",
    "mesh",
    "service-mesh",
    "istio",
    "envoy",
    "linkerd",
    "serverless",
    "lambda",
    "function",
    "functions",
    "edge1",
    "pop1",
    "point",
    "lb1",
    "lb2",
    "nlb",
    "alb",
    "elb",
    "ecs",
    "eks",
    "aks",
    "gke",
    "openshift",
    "rancher",
    "nomad",
    "swarm",
    "mesos",
    "terraform",
    "ansible1",
    "puppet",
    "chef",
    "packer",
    "vagrant1",
    "consul",
    "vault1",
    "observability",
    "tracing",
    "jaeger",
    "zipkin",
    "apm",
    "newrelic",
    "dynatrace",
    "appdynamics",
    "error",
    "errors",
    "exception",
    "exceptions",
    "debug1",
    "trace1",
    "profiler",
    "profiling",
    "benchmark",
    "loadtest",
    "stress",
    "chaos",
    "canary",
    "blue",
    "ab",
    "experiment",
    "feature",
    "features",
    "flag",
    "flags",
    "toggle",
    "a-b",
    "split",
    "variant",
    "variants",
    "i18n",
    "l10n",
    "translate",
    "translation",
    "locale1",
    "lang1",
    "language1",
    "multilingual",
    "rtl",
    "ltr",
    "arabic",
    "hebrew",
    "chinese",
    "en",
    "es",
    "fr1",
    "de1",
    "it",
    "pt",
    "ru",
    "zh",
    "ja1",
    "ko",
    "signup1",
    "onboarding",
    "welcome",
    "getting-started",
    "trial",
    "free",
    "premium",
    "enterprise",
    "business",
    "plan",
    "plans",
    "pricing",
    "subscribe",
    "subscription",
    "renew",
    "renewal",
    "cancel",
    "cancellation",
    "refund",
    "return1",
    "exchange3",
    "warranty",
    "coupon",
    "discount",
    "promo",
    "promotion",
    "deal",
    "offer",
    "offers",
    "special",
    "sale",
    "clearance",
    "loyalty",
    "rewards",
    "points",
    "program",
    "refer",
    "invitation",
    "invite",
    "share",
    "social1",
    "facebook",
    "twitter",
    "instagram",
    "linkedin",
    "youtube",
    "tiktok",
    "pinterest",
    "reddit",
    "bot1",
    "chatbot",
    "assistant",
    "virtual",
    "voice",
    "alexa",
    "siri",
    "cortana",
    "google-assistant",
    "ar",
    "vr",
    "xr",
    "metaverse",
    "3d",
    "print1",
    "3dprint",
    "manufacture",
    "factory",
    "supply",
    "chain",
    "procurement1",
    "quality",
    "qa1",
    "qc",
    "inspection",
    "testing1",
    "safety",
    "compliance1",
    "regulatory",
    "standard",
    "iso",
    "gdpr",
    "hipaa",
    "pci",
    "sox",
    "fedramp",
    "pentest",
    "security1",
    "infosec",
    "cybersec",
    "soc",
    "siem",
    "ids",
    "ips",
    "waf",
    "threat",
    "intel",
    "intelligence",
    "osint",
    "incident",
    "response",
    "forensics",
    "malware",
    "antivirus",
    "edr",
    "xdr",
    "mdr",
    "mssp",
    "server3",
    "server4",
    "server5",
    "host2",
    "host3",
    "host4",
    "web4",
    "web5",
    "web6",
    "www4",
    "www5",
    "app3",
    "app4",
    "app5",
    "ns9",
    "ns10",
    "mx3",
    "mx4",
    "mail4",
    "mail5",
    "ftp1",
    "ftp2",
    "sftp",
    "sftp1",
    "ftps",
    "db1",
    "db2",
    "db3",
    "db4",
    "db5",
    "sql1",
    "sql2",
    "nosql1",
    "nosql2",
    "cache2",
    "cache3",
    "redis2",
    "redis3",
    "node4",
    "node5",
    "node6",
    "node7",
    "node8",
    "worker1",
    "worker2",
    "worker3",
    "worker4",
    "proxy3",
    "proxy4",
    "proxy5",
    "vpn3",
    "vpn4",
    "vpn5",
    "dc4",
    "dc5",
    "dc6",
    "prometheus1",
    "grafana1",
    "kibana1",
    "elastic1",
    "logstash",
    "fluentd",
    "fluent",
    "loki",
    "kafka1",
    "kafka2",
    "kafka3",
    "zookeeper",
    "zk",
    "rabbitmq1",
    "rabbitmq2",
    "activemq",
    "celery",
    "consul1",
    "consul2",
    "etcd",
    "etcd1",
    "etcd2",
    "minio",
    "minio1",
    "ceph",
    "gluster",
    "nfs",
    "ldap1",
    "ldap2",
    "radius1",
    "kerberos",
    "git-lfs",
    "git-ssh",
    "git-http",
    "git-web",
    "wiki1",
    "wiki2",
    "mediawiki",
    "confluence1",
    "jira1",
    "jira2",
    "bamboo",
    "bitbucket1",
    "dev-db",
    "dev-cdn",
    "stg-db",
    "stg-cdn",
    "prod-db",
    "prod-cdn",
    "test-db",
    "test-api",
    "test-app",
    "test-web",
    "qa-db",
    "qa-api",
    "qa-app",
    "qa-web",
    "uat-db",
    "uat-api",
    "uat-app",
    "uat-web",
    "sonarqube",
    "sonar",
    "codeclimate",
    "codecov",
    "sentry1",
    "bugsnag",
    "rollbar",
    "raygun",
    "circleci",
    "travisci",
    "drone",
    "concourse",
    "argocd",
    "argo",
    "flux",
    "spinnaker",
    "harbor",
    "quay",
    "gcr",
    "ecr",
    "acr",
    "helm",
    "charts",
    "tiller",
    "istio1",
    "envoy1",
    "nginx1",
    "nginx2",
    "kong",
    "kong1",
    "apigee",
    "tyk",
    "wso2",
    "keycloak",
    "keycloak1",
    "hydra",
    "dex",
    "mfa",
    "2fa",
    "otp",
    "totp",
    "hr1",
    "payroll",
    "benefits",
    "timesheet",
    "erp2",
    "mrp",
    "wms",
    "tms",
    "pos",
    "terminal1",
    "kiosk",
    "atm",
    "branch",
    "agency",
    "office1",
    "clinic",
    "hospital",
    "doctor",
    "nurse",
    "school1",
    "university",
    "college",
    "academy",
    "library1",
    "archive1",
    "museum",
    "gallery1",
    "restaurant",
    "cafe",
    "bar",
    "kitchen",
    "gym",
    "fitness",
    "wellness",
    "spa1",
    "salon",
    "beauty",
    "barber",
    "auth-server",
    "token-server",
    "session-server",
    "notification-service",
    "email-service",
    "sms-service",
    "payment-service",
    "order-service",
    "user-service",
    "product-service",
    "catalog-service",
    "search-service",
    "recommendation",
    "suggest",
    "autocomplete",
    "upload-service",
    "media-service",
    "image-service",
    "video-service",
    "transcoding",
    "encoding",
    "analytics-service",
    "tracking-service",
    "event-service",
    "audit-service",
    "logging-service",
    "monitoring-service",
    "backup-service",
    "archive-service",
    "restore",
    "migration",
    "import",
    "export",
    "sync1",
    "scheduler",
    "cron",
    "job",
    "batch",
    "worker-service",
    "queue-service",
    "task-service",
    "us1",
    "us2",
    "us3",
    "eu1",
    "eu2",
    "eu3",
    "uk1",
    "uk2",
    "de2",
    "fr2",
    "jp1",
    "jp2",
    "cn1",
    "cn2",
    "au1",
    "au2",
    "in1",
    "in2",
    "sg",
    "sg1",
    "hk",
    "hk1",
    "kr",
    "kr1",
    "br",
    "br1",
    "mx5",
    "ca1",
    "ie",
    "ie1",
    "nl",
    "nl1",
    "se",
    "se1",
    "web-server",
    "app-server",
    "api-server",
    "db-server",
    "file-server",
    "mail-server",
    "dns-server",
    "ntp-server",
    "print-server",
    "proxy-server",
    "vpn-server",
    "log-server",
    "backup-server",
    "monitor-server",
    "build-server",
    "deploy-server",
    "test-server",
    "staging-server",
    "production-server",
    "frontend",
    "backend",
    "middleware",
    "gateway1",
    "ingress",
    "egress",
    "routing",
    "switch1",
    "storage1",
    "storage2",
    "san",
    "nas",
    "iscsi",
    "tape",
    "cold",
    "warm",
    "hot",
    "tier1",
    "tier2",
    "waf1",
    "ids1",
    "ips1",
    "firewall1",
    "antispam",
    "antimalware",
    "sandbox1",
    "honeypot",
    "decoy",
    "trap1",
    "canary1",
    "scan1",
    "scanner1",
    "vulnerability",
    "vuln",
    "patch1",
    "update1",
    "wsus",
    "sccm",
    "av",
    "dlp",
    "casb",
    "ztna",
    "sase",
    "portal1",
    "portal2",
    "selfservice",
    "self-service",
    "booking2",
    "reservation2",
    "appointment",
    "directory1",
    "directory2",
    "phonebook",
    "address",
    "contacts",
    "crm1",
    "crm2",
    "sales",
    "lead",
    "leads",
    "opportunity",
    "pipeline1",
    "funnel",
    "conversion",
    "campaign",
    "campaigns",
    "outreach",
    "drip",
    "newsletter",
    "digest",
    "weekly",
    "daily",
    "report1",
    "reports1",
    "bi1",
    "intelligence1",
    "forecast",
    "prediction",
    "model",
    "models",
    "training1",
    "inference",
    "serving",
    "deploy1",
    "vm1",
    "vm2",
    "vm3",
    "vm4",
    "vm5",
    "vps1",
    "vps2",
    "vps3",
    "rack1",
    "rack2",
    "rack3",
    "blade1",
    "blade2",
    "blade3",
    "pod1",
    "pod2",
    "pod3",
    "pod4",
    "shard1",
    "shard2",
    "shard3",
    "shard4",
    "partition1",
    "partition2",
    "partition3",
    "segment1",
    "segment2",
    "segment3",
    "cluster1",
    "cluster2",
    "cluster3",
    "farm1",
    "farm2",
    "farm3",
    "pool1",
    "pool2",
    "pool3",
    "group1",
    "group2",
    "group3",
    "set1",
    "set2",
    "set3",
    "ring1",
    "ring2",
    "ring3",
    "private1",
    "private2",
    "internal1",
    "internal2",
    "public1",
    "public2",
    "external1",
    "external2",
    "shared",
    "shared1",
    "shared2",
    "common",
    "global1",
    "local",
    "local1",
    "local2",
    "localhost",
    "loopback",
    "null",
    "void",
    "noop",
    "test4",
    "test5",
    "test6",
    "test7",
    "test8",
    "dev4",
    "dev5",
    "dev6",
    "dev7",
    "dev8",
    "lab1",
    "lab2",
    "lab3",
    "lab4",
    "poc",
    "poc1",
    "poc2",
    "concept",
    "proof",
    "experiment1",
    "trial1",
    "pilot",
    "mvp",
    "release1",
    "release2",
    "release3",
    "hotfix1",
    "hotfix2",
    "patch2",
    "patch3",
    "feature1",
    "feature2",
    "feature3",
    "branch1",
    "branch2",
    "fork",
    "fork1",
    "mirror",
    "mirror1",
    "mirror2",
    "replica1",
    "shadow",
    "shadow1",
    "shadow2",
    "standby",
    "standby1",
    "failover1",
    "failover2",
    "warm1",
    "cold1",
    "archive2",
    "archive3",
    "retention",
    "lifecycle",
    "cleanup",
    "purge",
    "rotate",
    "rotation",
    "cycle",
    "recycle",
    "health2",
    "alive",
    "ready",
    "startup",
    "init",
    "bootstrap",
    "setup1",
    "provision",
    "seed",
    "populate",
    "generate",
    "create",
    "build1",
    "compile",
    "package",
    "bundle",
    "minify",
    "compress",
    "optimize",
    "transform",
    "validate",
    "verify",
    "check",
    "assert",
    "gate",
    "guard",
    "sentinel",
    "watchdog",
    "daemon1",
    "service1",
    "process1",
    "thread",
    "io",
    "fs",
    "net",
    "sys",
    "os",
    "cpu",
    "memory",
    "mem",
    "disk",
    "gpu",
    "bandwidth",
    "throughput",
    "latency",
    "jitter",
    "uptime",
    "downtime",
    "maintenance",
    "outage",
    "incident1",
    "postmortem",
    "retrospective",
    "runbook",
    "playbook1",
    "procedure",
    "sop",
    "doc1",
    "docs1",
    "readme",
    "changelog",
    "todo",
    "backlog",
    "sprint",
    "kanban",
    "agile",
    "scrum",
    "lean",
    "devops1",
    "sre",
    "platform1",
    "infra",
    "infrastructure",
    "operations",
    "ops",
    "devops2",
    "gitops",
    "chatops",
    "noops",
    "aiops",
    "mlops",
    "dataops",
    "secops",
    "devsecops",
    "finops",
    "cloudops",
    "netops",
    "sysops",
    "admin3",
    "root",
    "superuser",
    "sudo",
    "operator",
    "manager",
    "supervisor",
    "director",
    "owner",
    "creator",
    "author",
    "editor",
    "viewer",
    "reader",
    "guest",
    "anonymous",
    "public-api",
    "private-api",
    "partner-api",
    "open-api",
    "closed-api",
    "internal-api",
    "v1-api",
    "v2-api",
    "v3-api",
    "v4-api",
    "rest-api",
    "soap-api",
    "graphql-api",
    "ws",
    "wss",
    "websocket",
    "socket",
    "socket1",
    "rtc",
    "webrtc",
    "signaling",
    "stun",
    "turn",
    "p2p",
    "peer",
    "peers",
    "mesh1",
    "gossip",
    "broadcast1",
    "multicast",
    "unicast",
    "anycast",
    "bravo",
    "charlie",
    "delta",
    "echo",
    "foxtrot",
    "golf",
    "india",
    "juliet",
    "kilo",
    "lima",
    "mike",
    "november",
    "oscar",
    "papa",
    "quebec",
    "romeo",
    "sierra",
    "tango",
    "uniform",
    "victor",
    "whiskey",
    "xray",
    "yankee",
    "zulu",
    "ac",
    "ad1",
    "ae",
    "af",
    "ag",
    "al",
    "am",
    "an",
    "ao",
    "aq",
    "as",
    "at",
    "aw",
    "ax",
    "az",
    "ba",
    "bb",
    "bc",
    "bd",
    "be",
    "bf",
    "bg",
    "bh",
    "bj",
    "bk",
    "bl",
    "bm",
    "bn",
    "bo",
    "bp",
    "bq",
    "bs",
    "bt",
    "bu",
    "bv",
    "bw",
    "bx",
    "by",
    "bz",
    "cb",
    "cc",
    "cd1",
    "ce",
    "cf1",
    "cg",
    "ch",
    "cj",
    "ck",
    "cl",
    "cm",
    "cn3",
    "co",
    "cp",
    "cq",
    "cr",
    "cs",
    "ct",
    "cu",
    "cw",
    "cx",
    "cy",
    "cz",
    "da",
    "db6",
    "dd",
    "df",
    "dg",
    "dh",
    "di",
    "dj",
    "dk",
    "dl",
    "dm",
    "dn",
    "do1",
    "dp",
    "dq",
    "dr1",
    "ds",
    "dt",
    "du",
    "dv",
    "dw",
    "dx",
    "dy",
    "dz",
    "ea",
    "eb",
    "ec",
    "ed",
    "ee",
    "ef",
    "eg",
    "eh",
    "ei",
    "ej",
    "ek",
    "el",
    "em",
    "en1",
    "eo",
    "ep",
    "eq",
    "er",
    "es1",
    "et",
    "eu4",
    "ev",
    "ew",
    "ex",
    "ey",
    "ez",
    "fa",
    "fb",
    "fc",
    "fd",
    "fe",
    "ff",
    "fg",
    "fh",
    "fi",
    "fj",
    "fk",
    "fl",
    "fm1",
    "fn",
    "fo",
    "fp",
    "fq",
    "fs1",
    "ft",
    "fu",
    "fv",
    "fw1",
    "fx",
    "fy",
    "fz",
    "ga",
    "gb",
    "gc",
    "gd",
    "ge",
    "gf",
    "gg",
    "gh",
    "gi",
    "gj",
    "gk",
    "gl",
    "gm",
    "gn",
    "go1",
    "gp",
    "gq",
    "gr",
    "gs",
    "gt",
    "gu",
    "gv",
    "gw1",
    "gx",
    "gy",
    "gz",
    "ha",
    "hb",
    "hc",
    "hd",
    "he",
    "hf",
    "hg1",
    "hh",
    "hi",
    "hj",
    "staging-api",
    "staging-app",
    "staging-web",
    "staging-cdn",
    "prod-static",
    "dev-static",
    "stg-static",
    "payments-api",
    "orders-api",
    "users-api",
    "auth-service",
    "identity-service",
    "gateway-api",
    "admin-service",
    "notification-api",
    "messaging-api",
    "chat-api",
    "file-api",
    "document-api",
    "report-api",
    "export-api",
    "import-api",
    "webhook-api",
    "integration-api",
    "third-party",
    "vendor-api",
    "partner-service",
    "customer-portal",
    "admin-portal",
    "partner-portal",
    "vendor-portal",
    "employee-portal",
    "student-portal",
    "teacher-portal",
    "parent-portal",
    "agent-portal",
]



# =============================================================================
# API KEY MANAGEMENT
# =============================================================================

def load_api_keys():
    """
    Load API keys from environment variables or a config file.

    Checks the following sources in order:
    1. Environment variables (MONSTER_SHODAN_KEY, MONSTER_CENSYS_ID, etc.)
    2. ~/.monster/api_keys.json
    3. ./monster_config.json

    Returns:
        dict: Dictionary of API keys with service names as keys.
    """
    keys = {
        "shodan": None,
        "censys_id": None,
        "censys_secret": None,
        "virustotal": None,
        "securitytrails": None,
        "hunter": None,
        "builtwith": None,
        "whoisxml": None,
        "urlscan": None,
        "github": None,
        "gitlab": None,
        "slack_webhook": None,
        "discord_webhook": None,
        "telegram_bot": None,
        "telegram_chat_id": None,
    }

    # Try environment variables first
    env_mapping = {
        "shodan": "MONSTER_SHODAN_KEY",
        "censys_id": "MONSTER_CENSYS_ID",
        "censys_secret": "MONSTER_CENSYS_SECRET",
        "virustotal": "MONSTER_VIRUSTOTAL_KEY",
        "securitytrails": "MONSTER_SECURITYTRAILS_KEY",
        "hunter": "MONSTER_HUNTER_KEY",
        "builtwith": "MONSTER_BUILTWITH_KEY",
        "whoisxml": "MONSTER_WHOISXML_KEY",
        "urlscan": "MONSTER_URLSCAN_KEY",
        "github": "MONSTER_GITHUB_TOKEN",
        "gitlab": "MONSTER_GITLAB_TOKEN",
        "slack_webhook": "MONSTER_SLACK_WEBHOOK",
        "discord_webhook": "MONSTER_DISCORD_WEBHOOK",
        "telegram_bot": "MONSTER_TELEGRAM_BOT_TOKEN",
        "telegram_chat_id": "MONSTER_TELEGRAM_CHAT_ID",
    }

    for key_name, env_var in env_mapping.items():
        value = os.environ.get(env_var)
        if value:
            keys[key_name] = value

    # Try config files
    config_paths = [
        Path.home() / ".monster" / "api_keys.json",
        Path("monster_config.json"),
        Path(".monster_keys.json"),
    ]

    for config_path in config_paths:
        if config_path.exists():
            try:
                with open(config_path, "r") as f:
                    file_keys = json.load(f)
                for key_name in keys:
                    if keys[key_name] is None and key_name in file_keys:
                        keys[key_name] = file_keys[key_name]
            except (json.JSONDecodeError, IOError, OSError):
                pass

    return keys
